apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 876278990625.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 876278990625.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 7f2a65d2
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
